/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Test_App;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.io.FileNotFoundException;
import java.io.IOException;

public class AppTest {
    @Test
    public void getInstanceTest () {
        Storage storage = Storage.getInstance();
        assert storage != null;
    }

    @Test
    public void getAddTransaction() {
        Storage storage = Storage.getInstance();
        Transaction transaction = new Transaction("Salary", 200);
        storage.addTransaction(transaction);
        assert storage.getLoadedTransactions().contains(transaction);
    }

    @Test
    public void getSaveFile() throws IOException {
        Storage storage = Storage.getInstance();
        assertDoesNotThrow(() -> storage.saveFile());
    }

    @Test
    public void getRead() throws FileNotFoundException {
        Storage storage = Storage.getInstance();
        storage.read();
        assertNotNull(storage.getLoadedTransactions());
    }

    @Test
    public void getReadCatch(){
        Storage storage = Storage.getInstance();
        storage.deleteFile();
        assertThrows(FileNotFoundException.class, () -> storage.read());
    }
}
